spring:
  datasource:
    url: "jdbc:h2:mem:employee-management"
  h2:
    console:
      enabled: true
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: "/api"
  error:
    include-message: always
